### ISSUE TITLE
A bug with typechecking fields of dataclasses with default values/factories

### ISSUE THREAD

**Issue by knyazer** [google/jaxtyping#114] opened 2023-09-21 12:59 UTC
It seems like jaxtyping is quite struggling when trying to process ```dataclasses.field```s:
```
import equinox as eqx
import jax.numpy as jnp
import jaxtyping as jt
from jaxtyping import jaxtyped
from beartype import beartype

@jaxtyped
@beartype
class A(eqx.Module):
  x: jt.Int[jt.Array, ""] = eqx.field(default=0, converter=jnp.asarray)

A(1)
```
throws 
``` BeartypeCallHintParamViolation: Method __main__.A.__init__() parameter x=1 violates type hint <class 'jaxtyping.Int[Array, '']'>, as int 1 not instance of <protocol "jaxtyping.Int[Array, '']">. ```

which is clearly incorrect, because of the converter. The solution that could be possible is to wrap function passed to ```converter``` into jaxtyping decorators, instead of the ```__init__``` method, but, since some parameters should be checked on ```__init__``` level, and some on the ```converter``` level it seems cumbersome to implement something like that.

The problem is that this issue effectively forces to use incorrect type annotation for ```x```: one cannot not define a type, and not allowed to define a correct type. And, using incorrect type annotations seems an extremely annoying thing to do... 

What do you think, Patrick?

**Comment by knyazer** [comment] 2023-09-21 13:13
```
ast.dump(ast.parse("""
class A:
  x: jt.Int[jt.Array, ""] = eqx.field(default=0, converter=jnp.asarray)
""").body[0])
```
gives
```
AnnAssign(
    target=Name(id='x', ctx=Store()), 
    annotation=Subscript(...)
    value=Call(
        func=Attribute(value=Name(id='eqx', ctx=Load()), attr='field', ctx=Load()), 
        args=[], 
        keywords=[keyword(arg='default', value=Constant(value=0)), 
                  keyword(arg='converter', value=Attribute(value=Name(id='jnp', ctx=Load()), attr='asarray', ctx=Load()))]
        ), simple=1
    )
```
It seems like the only way to deal with fields for which any value at all is assigned, is to wrap the assigned value into the decorator, and ignore the typechecking for this parameter on ```__init__```. And this is quite a bit of work, overall. But, since I think you were planning overhaul of the hooks anyway, maybe does not hurt much to implement it?

**Comment by patrick-kidger** [comment] 2023-09-21 15:45
Right, this is a known wart that I've not seen an obvious answer to. The problem is that the type annotation is used in two places: both in the autogenerated `__init__`, and for the type of the attribute that is eventually set on the dataclass. 

What this boils down to is that the same annotation is used for both the input and the output of `converter`.

I think the fix might be to remove the typechecking for `YourDataclass.__init__` altogether, and instead implement type-checking as an extra pass that happens after initialisation. That is, iterate over `fields(your_dataclass_instance)` and check that the types match.

WDYT?

**Comment by knyazer** [comment] 2023-09-21 20:32
Your solution seems nice. So, to sum up, here are the cases:

1. if we have a class with autogenerated ```__init__``` method, we want to ignore parameters of ```__init__```, but do a check after ```__init__``` is completed.
2. If we have a class with user-defined ```__init__```, we want to do a check both for parameters and after ```__init__``` is done.
3. We want to do a typecheck on all the default fields after conversion -> the same as doing post-```__init__``` typecheck.

The problem is distinguishing user-defined ```__init__``` from non-user-defined ones. And, it seems that when one is using beartype it is quite problematic:
```
from beartype import beartype
import equinox as eqx

@beartype
class F(eqx.Module):
    foo: list[int] = eqx.field(converter=lambda x: [x])
print(F([1]).foo)
```
Beartype does not catch the existence of the converter, and so it throws. The obvious way to deal with it is to force beartype to ignore ```__init__```. And, if the ```__init__``` is defined (by a user) we need to typecheck it. Here is a citation from [beartype docs](https://beartype.readthedocs.io/en/latest/api_decor/#api-decor-noop):
```
You must decorate classes (rather than merely methods) with beartype to type-check the following: ...

The standard dataclasses decorator dynamically generates 
and adds new dunder methods (e.g., __init__(), __eq__(), 
__hash__()) to the decorated class. These methods do not 
physically exist and thus cannot be decorated directly with 
beartype. Instead, you must decorate dataclasses first by 
@beartype and then by @dataclasses.dataclass. Order is 
significant, of course. 
```
Looks like this is a way to go, since decorating methods would allow us to ignore typechecking all the logic introduced by the dataclasses, or by other decorators. Like this:
```
import dataclasses
from beartype import beartype
import equinox as eqx

class F1(eqx.Module):
    foo: list[int] = eqx.field(converter=lambda x: [x])

    @beartype
    def do_something():
      ...

print(F1(0).foo) # doesn't fail

@beartype
class F2(eqx.Module):
    foo: list[int] = eqx.field(converter=lambda x: [x])

    def do_something():
      ...

print(F2(0).foo) # fails
```

Though this solution still seems a bit ugly: maybe there is some 'useful' typechecking to be done introduced by these generated methods? However, it seems to be relatively hard to detect that the ```__init__``` was introduced in the decorator, and then maybe decorate it again, so that generated ```__init__``` is now not type-checked. Probably this can be done with detecting the ```__init__``` via the ast parsing, but I feel like there are cases which this won't handle well.


Yeah, overall it looks like post-init typechecking is a really nice idea, but ignoring the types of ```__init__``` that was generated by decorators seems non-trivial. I wonder if you can come up with another smart solution to deal with this.

**Comment by knyazer** [comment] 2023-09-21 20:43
Actually, all the negative things that come from doing method-annotation with beartype are already there: it is exactly the issue with typing.Self mentioned here #92 . Meaning is that only a post-check needed, since the part with ignoring some ```__init__```s is already working. It's not a bug, it's a feature :smile:

**Comment by patrick-kidger** [comment] 2023-09-22 17:07
Hah! Yup, this starts getting quite subtle.

But you do raise a good point, which is that user-defined `__init__` methods should still be checked when they're called. So I think we need to (a) apply [this line](https://github.com/google/jaxtyping/blob/e05985df2b37e7849f8a02f8b493759a161c5967/jaxtyping/_decorator.py#L147) conditional on whether it's user-defined or not, and (b) probably do something evil like this:
```python
# Call this function in the same place as the link above
def _substitute_metaclass(datacls, typechecker):
    class CheckedDataclassMeta(type(datacls)):
        def __call__(cls, *args, **kwargs):
            self = super(CheckedDataclass, cls).__call__(*args, **kwargs)
            _check_annotations(self, typechecker)
            return self

    dataclas.__class__ = CheckedDataclassMeta
    return datacls

@jaxtyped
def _check_annotations(self, typechecker):
    for field in dataclass.fields(self):
        for kls in cls.__mro__:
            try:
                annotation = kls.__annotations__[field.name]
            except KeyError:
                pass
            else:
                break
        else:
            raise TypeError
        try:
            value = getattr(self, field.name)
        except AttributeError:
            continue  # allow uninitialised fields, which are valid on dataclasses in general

         @typechecker
         def typecheck(x: annotation):
             pass

         typecheck(value)
```

(
Notably just adding the checks to the end of the `__init__` method isn't enough, as [Equinox's converter runs after that](https://github.com/patrick-kidger/equinox/blob/76a13bd100a8127c7e5176f2dee9d36c837b46ec/equinox/_module.py#L196-L202), so that things like
```python
foo: Array = eqx.field(converter=jnp.asarray)
bar: int
def __init__(...):
    self.foo = 1
    self.bar = 1 + self.foo
```
will work, i.e. `self.foo` isn't converted on assignment.
)

**Comment by knyazer** [comment] 2023-09-23 18:39
So, I thought quite a bit on this topic, and I think that there are a few interconnected issues that bother me, both with your solution, and the design of ```equinox.field```. I mean, your solution would work alright, but I just feel that doing metaclass substitution is a bad way to resolve a problem: I am biased though, because I don't think that I ever used such an approach. In short, my solution is based over using ```__post_init__``` to solve all the problems in the world.

For starters, running Equinox's converter after the ```__init__``` in the way it is done now, does not only look not ergonomic, but also could potentially lead to an undebuggable behavior:
```
class A(eqx.Module):
    field: list[int] = eqx.field(converter=lambda x: [x])

class B(A):
  def __init__(self, x):
    self.field = x

B([1]).field # [[1]]
```
You could imagine that ```A``` is somewhere in the library, hidden from the user, and ```B``` is a user-defined class. Then, the user would have a wonderful situation, because the behavior of ```B``` is inexplicable, from the viewpoint of a person who does not know how ```converter``` works.

I think it makes the most sense to apply ```converter``` only when the ```__init__``` was autogenerated by the dataclass: otherwise, it leads to unexpected behaviour of ```__init__``` method. And, the documentation about the ```eqx.field``` on the website does not mention anything about this complexity.


There is a much nicer solution that I discovered, though I am not sure if it is actually possible to realize it: it is to use ```__post_init__``` method [linkie](https://docs.python.org/3/library/dataclasses.html#post-init-processing). This method is applied to the dataclass only if ```__init__``` was self generated too, so if it is user-defined, it is not called. Thus it makes a lot of sense to put all the ```converter``` and post-init typechecking logic into the post_init. I played around a bit with it, and it looks like it could work, and allow for much nicer solution than the one we currently have.

So, my plan is as follows:
* make ```eqx._ModuleMeta.__call__``` to assign a wrapped ```__post_init__``` to ```initable_cls```, [here](https://github.com/patrick-kidger/equinox/blob/76a13bd100a8127c7e5176f2dee9d36c837b46ec/equinox/_module.py#L184C9-L184C9) something like that: 
```
 def custom_post_init(self):
    apply_converter()
    user_defined_post_init()
initable_cls.__post_init__ = custom_post_init
self = super(...
````
* make jaxtyping do the post-```__post_init__``` typecheck, so wrap the jaxtyped class's ```__post_init__``` into something, that would run user-(equinox)-defined ```__post_init__``` and then typecheck all the fields. The issue here is that we don't check if user defined custom ```__init__```: something like this is still possible ```
a: list[int]
def __init__(self):
   self.a = [1.0]
``` but this case I guess can be fixed by adding typechecking of fields to the end of the user-defined ```__init__```. Hence, the typechecking for user-defined ```__init__``` would happen in the end of it, and for dataclass generated ```__init__``` it will happen in the end of the ```__post_init__``` which is quite ergonomic, I reckon.
* make jaxtyping ignore generated-```__init__``` annotations.

WDYT? If you OK with the proposal, I could work on the PRs to jaxtyping/equinox over the next week or so. Or, would be great if you can propose something even more beatiful.

**Comment by patrick-kidger** [comment] 2023-09-25 17:53
I like your suggestion! I think it's particularly good just because it simplifies what jaxtyping needs to do. And I completely take your example that running `converter` like this could be surprising for an end-user.

However, good reasons not to do this:

(a) it may be confusing to have cases in which `converter` *doesn't* run, even thought you've defined it;

(b) it'd be a small compatibility break;

(c) it's not what attrs does:
```python
>>> import attr
>>> @attr.s
... class C:
...     x: int = attr.ib(converter=int)
...     def __init__(self, x):
...             self.x = x
... 
>>> C("1").x
1
```

---

I've got an alternate suggestion: we could move conversion to unconditionally happen between `__init__` and `__post_init__`? Good reasons for this are that (a) this would still make it easy to implement this change in jaxtyping, and (b) would also match attrs:
```python
>>> @attr.s                                                                                                                                                                                                       
... class C:                                                                                                                                                                                            
...     x: int = attr.ib(converter=int)                                                                                                                                                                           
...     def __init__(self, x):                                                                                                                                                                                    
...             self.x = x                                                                                                                                                                                        
...     def __attrs_post_init__(self):                                                                                                                                                                            
...             print(self.x, type(self.x))                                                                                                                                                                       
... 
>>> C("1")
1 <class 'int'>
C(x=1)
```
Of course, this doesn't solve your example in which `A` and `B` are highly separated, but I don't think there's really a solution for that: it's arguably also surprising to have the converter *not* run for `B`.

[
Implementation note for this suggestion. I'm aware that a custom `__init__` means that `__post_init__` isn't run at all, so the above is "morally speaking". In practice if there's a dataclass-provided `__init__` then we add conversion to the start of `__post_init__` (as the dataclass-provided `__init__` calls `__post_init__`, so this is the only way to insert it there), whilst if there's a user-provided `__init__` then we add conversion to the end of `__init__` (as `__post_init__` isn't then called at all). Note that Equinox already tracks whether a class has a dataclass-provided `__init__` or not so doing the gating there would be easy (`equinox._module._has_dataclass_init`).
]

---

A few more thoughts on your A-and-B surprising example.

I think the real culprit here is that you defined a field on an ABC. I believe this is an antipattern -- IMO an ABC should never have an `__init__` method and should never have concrete fields. Rather, both of these things should be left to the concrete class:
```python
class A(eqx.Module):
    field: AbstractVar[list[int]]  # You now know that `def f(x: A): print(x.field)` is safe to write

class B(A):
  # if the abstract field isn't declared then `B(...)` will raise an error on initialisation
  field: list[int] = eqx.field(converter=lambda x: [x])

  def __init__(self, x):
    self.field = x

B([1]).field  # no surprises here, you had to put it all in `B`!
```

I still want to tighten the wording a bit, but the next Equinox release will include these recommendations [in the documentation](https://github.com/patrick-kidger/equinox/blob/d9b018ad61c0dcd1835ed558c4820a51f9476fe8/docs/pattern.md). It will also include a flag `class Foo(eqx.Module, strict=True)` you can use to enforce this if you wish.

---

Alright, that's a lot. WDYT?

**Comment by patrick-kidger** [comment] 2023-09-26 05:50
---

Update: I spent a bit of today wrestling with this. I don't think messing with `__init__` (or `__post_init__`) is going to work. The reason basically boils down to the fact that users may or may not call `super().__init__()`, and if they do then they may then trigger these checks too early.

I think back to plan A, messing with the metaclass `__call__`, may actually be the cleanest thing to do...

**Comment by knyazer** [comment] 2023-09-26 09:53
Alright, so I am just going to address some parts of your response, since it is quite detailed.



> (a) it may be confusing to have cases in which `converter` _doesn't_ run, even thought you've defined it;

Yes, that is annoying. I think we probably need a bit more information in the documentation about it? Even though converter is advanced feature, I find its behaviour a bit unexpected, so would be nice if we can align the expectations of the users with this particular behaviour via some nice explanation. ```attr``` applies ```converter``` in a similar fashion, but I am guessing that ```attr``` itself is not perfect, and since this functionality is not supported by dataclasses by default, it seems sensible to explain what exactly we do. 



> It will also include a flag `class Foo(eqx.Module, strict=True)`

Oh, adding the flag is an extremely nice idea, I think I even wanted to propose it at some point, but I don't remember what was the problem to which strict-mode was the solution...





> I think the real culprit here is that you defined a field on an ABC. I believe this is an antipattern

Yes, of course. But I think it is an ill approach to say something in the lines of "if you don't use the design pattern we want, your code will behave arbitrarily. Good luck!". Probably there are cases when inheritance with partial implementations is necessary. But anyway, this is also related to your latter comment: if we force people to use this design pattern, there is never a call to ```super().__init__```. In this particular case I think this makes some sense (yes, I firstly critique your proposal, and then I approve of it), because I cannot really think what is the expected behaviour of ```converter``` when doing ```super().__init__```. Probably we could even raise it as an error in this case, since, the user might expect either conversion after his ```__init__``` or conversion after ```super().__init__``` or no conversion at all. Like in my A-B example, there are all three variants of the conversion possible if we add ```super().__init__``` to the init of B. 

I think we can safely ignore that user could to call ```super().__init__``` because it breaks the design pattern. Citing from the design pattern document you attached: ```abstract classes should not define __init__ methods``` meaning that the expected behaviour of ```super().__init__``` should be just a naive assignment of the variable values to fields (since there are no converters and no __init__). So putting conversion logic inbetween ```__init__``` and ```__post_init__``` still works, and typechecking on the fields can be put in the end of ```__post_init__``` (for abstract classes) or the end of ```__init__``` (for final classes). My brain is actually not able to handle such number of conditions efficiently, so I think I am going to make up some sort of a diagram and write down all the cases, and then share it here, if it is going to work. And if not, I am going to share that it does not work :)

I just really want to make the ```__init__/__post_init__``` wrapping work, instead of doing metaclass substitution.

**Comment by patrick-kidger** [comment] 2023-09-26 17:47
1) I've just written https://github.com/patrick-kidger/equinox/pull/519, which for the dataclass-init case, moves conversion to happen before `__post_init__` It also documents when the conversion is ran. That's at least an improvement on the status quo.

2) You state

    > I think we can safely ignore that user could to call super().__init__ because it breaks the design pattern.

    but then also say

    > But I think it is an ill approach to say something in the lines of "if you don't use the design pattern we want, your code will behave arbitrarily. Good luck!"

    ;)

    I definitely think we should support users calling `super().__init__`, even if we never do it ourselves. Unfortunately, I think that means it'll be impossible for jaxtyping to patch its checks into `__init__` or `__post_init__` -- because they checks may then be ran too early by a subclass accessing it via `super().__{init,post_init}__`.

    (
    `eqx.nn` itself actually has a few `super()`s in there to support co-operative multiple inheritance, just-in-case downstream users want to do that. I may anyway remove them at some point, to standardise on usage of the abstract/final pattern across the Equinox ecosystem, but that's something to think about later.
    )

    So whilst it's not pretty, I think the metaclass patching may really be the only way to do this.

3) On the plus side, I've realised that the above is the *only* thing jaxtyping has to do. If a user defines a custom `__init__` method then this will be picked up by the AST transformer and checked. If there is a dataclass-provided `__init__` then this does not appear in the AST and it is not checked. Either way, that's what we want.

**Comment by knyazer** [comment] 2023-09-27 08:43
Alright, I agree with you on all the points. Thanks for making a PR to Equinox about it.


> 3\. If a user defines a custom `__init__` method then this will be picked up by the AST transformer and checked.

I think the AST transformer needs a decently large rewrite anyway, (see, for example, #92), which could change its behaviour significantly, so I am guessing it would be sensible to work on both this and the aforementioned issue together, since they might affect each other. Also, I am quite sure that when one solves #92, it leads to ```@beartype``` actually annotating dataclass-generated methods, so yes, there are some non-obvious things to be done.

But overall, thanks for the discussion! It is quite sad that the method with ```__post_init__```  didn't work out.

**Comment by patrick-kidger** [comment] 2023-09-27 15:48
> Also, I am quite sure that when one solves https://github.com/google/jaxtyping/issues/92, it leads to @beartype actually annotating dataclass-generated methods, so yes, there are some non-obvious things to be done.

Yup, this is probably an issue for us now! Another complication is that beartype recently introduced their own import hook (via some other mechanism that hooks into `importlib` I believe), and it'd be nice to be compatible with that too. Their hook is actually a bit better than the one we've got, in that it also checks types of assignments (`x: Foo = make_foo()`), not just arguments and return types.

Given that that's now a fairly hairy topic, I think I'll write a jaxtyping PR implementing the metaclass `__call__` approach first. At least fix up this issue to get us into a stable spot, before tackling something more complicated.

> But overall, thanks for the discussion!

Likewise! This has done a lot to clarify what makes for a good approach; I appreciate you taking the time.

**Comment by patrick-kidger** [comment] 2023-09-28 01:06
Okay! Check out #119, which fixes this. jaxtyping-of-a-dataclass should now check the fields that the dataclass has assigned, and not the `__init__` method.

By the way, you'll like this: it turns out that the metaclass-`__call__` approach doesn't work, because Python doesn't allow you to reassign metaclasses. Whoops! I managed to figure out an `__init__`-time checking approach after all -- a check of the form `if self.__class__.__init__ is cls.__init__` can be used to detect whether or not you're in a `super()` call, so we can avoid running checks then.

**Comment by patrick-kidger** [comment] 2023-10-21 21:16
Closing as completed.

**Closed by patrick-kidger** 2023-10-21 21:16 UTC
Labels: feature
